179 ./app/Features/Transactions/Presentation/Views/index.blade.php
120 ./app/Features/Transactions/Presentation/Views/edit.blade.php
104 ./app/Features/Transactions/Presentation/Views/show.blade.php
111 ./app/Features/Transactions/Presentation/Views/create.blade.php
99 ./app/Features/Transactions/Presentation/Http/Controllers/TransactionController.php
52 ./app/Features/Transactions/Presentation/Http/Presenters/ShowTransactionsPaginationPresenter.php
38 ./app/Features/Transactions/Presentation/Http/Presenters/StoreTransactionPresenter.php
45 ./app/Features/Transactions/Presentation/Http/Presenters/UpdateTransactionPresenter.php
36 ./app/Features/Transactions/Presentation/Http/Presenters/DestroyTransactionPresenter.php
52 ./app/Features/Transactions/Presentation/Http/Presenters/ShowTransactionPresenter.php
61 ./app/Features/Transactions/Presentation/Http/Presenters/EditTransactionPresenter.php
44 ./app/Features/Transactions/Presentation/Http/Requests/StoreTransactionRequest.php
44 ./app/Features/Transactions/Presentation/Http/Requests/UpdateTransactionRequest.php
42 ./app/Features/Transactions/Infrastructure/Providers/TransactionServiceProvider.php
10 ./app/Features/Transactions/Application/Outputs/UpdateTransactionOutput.php
11 ./app/Features/Transactions/Application/Outputs/DestroyTransactionOutput.php
11 ./app/Features/Transactions/Application/Outputs/ShowTransactionOutput.php
10 ./app/Features/Transactions/Application/Outputs/StoreTransactionOutput.php
14 ./app/Features/Transactions/Application/Outputs/EditTransactionOutput.php
14 ./app/Features/Transactions/Application/Outputs/ShowTransactionsPaginationOutput.php
8 ./app/Features/Transactions/Application/Contracts/ShowTransactionsPaginationContract.php
9 ./app/Features/Transactions/Application/Contracts/DestroyTransactionContract.php
9 ./app/Features/Transactions/Application/Contracts/ShowTransactionContract.php
10 ./app/Features/Transactions/Application/Contracts/StoreTransactionContract.php
10 ./app/Features/Transactions/Application/Contracts/UpdateTransactionContract.php
10 ./app/Features/Transactions/Application/Contracts/EditTransactionContract.php
28 ./app/Features/Transactions/Application/Usecases/StoreTransactionUsecase.php
28 ./app/Features/Transactions/Application/Usecases/EditTransactionUsecase.php
23 ./app/Features/Transactions/Application/Usecases/ShowTransactionsPaginationUsecase.php
30 ./app/Features/Transactions/Application/Usecases/ShowTransactionUsecase.php
22 ./app/Features/Transactions/Application/Usecases/DestroyTransactionUsecase.php
29 ./app/Features/Transactions/Application/Usecases/UpdateTransactionUsecase.php
191 ./app/Features/EstateUtilityServices/Presentation/Views/index.blade.php
152 ./app/Features/EstateUtilityServices/Presentation/Views/edit.blade.php
214 ./app/Features/EstateUtilityServices/Presentation/Views/show.blade.php
141 ./app/Features/EstateUtilityServices/Presentation/Views/create.blade.php
110 ./app/Features/EstateUtilityServices/Presentation/Http/Controllers/EstateUtilityServicesController.php
41 ./app/Features/EstateUtilityServices/Presentation/Http/Presenters/CreateEstateUtilityServicePresenter.php
47 ./app/Features/EstateUtilityServices/Presentation/Http/Presenters/UpdateEstateUtilityServicePresenter.php
62 ./app/Features/EstateUtilityServices/Presentation/Http/Presenters/ShowEstateUtilityServicePresenter.php
37 ./app/Features/EstateUtilityServices/Presentation/Http/Presenters/DestroyEstateUtilityServicePresenter.php
63 ./app/Features/EstateUtilityServices/Presentation/Http/Presenters/EditEstateUtilityServicePresenter.php
60 ./app/Features/EstateUtilityServices/Presentation/Http/Presenters/ShowAllEstateUtilityServicesPresenter.php
39 ./app/Features/EstateUtilityServices/Presentation/Http/Presenters/StoreEstateUtilityServicePresenter.php
49 ./app/Features/EstateUtilityServices/Presentation/Http/Requests/UpdateEstateUtilityServiceRequest.php
45 ./app/Features/EstateUtilityServices/Presentation/Http/Requests/StoreEstateUtilityServiceRequest.php
48 ./app/Features/EstateUtilityServices/Infrastructure/Providers/EstateUtilityServicesServiceProvider.php
9 ./app/Features/EstateUtilityServices/Application/Outputs/StoreEstateUtilityServiceOutput.php
10 ./app/Features/EstateUtilityServices/Application/Outputs/EditEstateUtilityServiceOutput.php
17 ./app/Features/EstateUtilityServices/Application/Outputs/ShowAllEstateUtilityServicesOutputs.php
10 ./app/Features/EstateUtilityServices/Application/Outputs/ShowEstateUtilityServiceOutput.php
8 ./app/Features/EstateUtilityServices/Application/Outputs/DestroyEstateUtilityServiceOutput.php
17 ./app/Features/EstateUtilityServices/Application/Outputs/CreateEstateUtilityServiceOutput.php
8 ./app/Features/EstateUtilityServices/Application/Outputs/UpdateEstateUtilityServiceOutput.php
12 ./app/Features/EstateUtilityServices/Application/Contracts/EditEstateUtilityServiceContract.php
9 ./app/Features/EstateUtilityServices/Application/Contracts/DestroyEstateUtilityServiceContract.php
8 ./app/Features/EstateUtilityServices/Application/Contracts/CreateEstateUtilityServiceContract.php
8 ./app/Features/EstateUtilityServices/Application/Contracts/ShowEstateUtilityServiceContract.php
9 ./app/Features/EstateUtilityServices/Application/Contracts/StoreEstateUtilityServiceContract.php
8 ./app/Features/EstateUtilityServices/Application/Contracts/ShowAllEstateUtilityServicesContract.php
13 ./app/Features/EstateUtilityServices/Application/Contracts/UpdateEstateUtilityServiceContract.php
35 ./app/Features/EstateUtilityServices/Application/Usecases/EditEstateUtilityServiceUsecase.php
31 ./app/Features/EstateUtilityServices/Application/Usecases/CreateEstateUtilityServiceUsecase.php
27 ./app/Features/EstateUtilityServices/Application/Usecases/UpdateEstateUtilityServiceUsecase.php
34 ./app/Features/EstateUtilityServices/Application/Usecases/ShowEstateUtilityServiceUsecase.php
22 ./app/Features/EstateUtilityServices/Application/Usecases/DestroyEstateUtilityServiceUsecase.php
28 ./app/Features/EstateUtilityServices/Application/Usecases/StoreEstateUtilityServiceUsecase.php
28 ./app/Features/EstateUtilityServices/Application/Usecases/ShowAllEstateUtilityServicesUsecase.php
7 ./app/Features/Dashboard/Presentation/Views/index.blade.php
13 ./app/Features/Dashboard/Presentation/Http/Controllers/DashboardController.php
25 ./app/Features/Dashboard/Infrastructure/Providers/DashboardServiceProvider.php
162 ./app/Features/Renters/Presentation/Views/index.blade.php
136 ./app/Features/Renters/Presentation/Views/edit.blade.php
105 ./app/Features/Renters/Presentation/Views/show.blade.php
121 ./app/Features/Renters/Presentation/Views/create.blade.php
101 ./app/Features/Renters/Presentation/Http/Controllers/RenterController.php
67 ./app/Features/Renters/Presentation/Http/Presenters/EditRenterPresenter.php
35 ./app/Features/Renters/Presentation/Http/Presenters/StoreRenterPresenter.php
50 ./app/Features/Renters/Presentation/Http/Presenters/ShowRenterPresenter.php
61 ./app/Features/Renters/Presentation/Http/Presenters/ShowRenterPaginatePresenter.php
34 ./app/Features/Renters/Presentation/Http/Presenters/DestroyRenterPresenter.php
46 ./app/Features/Renters/Presentation/Http/Presenters/UpdateRenterPresenter.php
75 ./app/Features/Renters/Presentation/Http/Requests/UpdateRenterRequest.php
75 ./app/Features/Renters/Presentation/Http/Requests/StoreRenterRequest.php
41 ./app/Features/Renters/Infrastructure/Providers/RenterServiceProvider.php
11 ./app/Features/Renters/Application/DTOs/RenterEntitiesWithPagination.php
10 ./app/Features/Renters/Application/Outputs/StoreRenterOutput.php
11 ./app/Features/Renters/Application/Outputs/ShowRenterOutput.php
12 ./app/Features/Renters/Application/Outputs/EditRenterOutput.php
18 ./app/Features/Renters/Application/Outputs/ShowRentersPaginationOutput.php
9 ./app/Features/Renters/Application/Outputs/DestroyRenterOutput.php
8 ./app/Features/Renters/Application/Outputs/UpdateRenterOutput.php
12 ./app/Features/Renters/Application/Contracts/EditRenterContract.php
12 ./app/Features/Renters/Application/Contracts/ShowRenterContract.php
8 ./app/Features/Renters/Application/Contracts/ShowRentersPaginationContract.php
9 ./app/Features/Renters/Application/Contracts/DestroyRenterContract.php
17 ./app/Features/Renters/Application/Contracts/StoreRenterContract.php
10 ./app/Features/Renters/Application/Contracts/UpdateRenterContract.php
26 ./app/Features/Renters/Application/Usecases/StoreRenterUsecase.php
25 ./app/Features/Renters/Application/Usecases/ShowPaginateRenterUsecase.php
21 ./app/Features/Renters/Application/Usecases/DestroyRenterUsecase.php
27 ./app/Features/Renters/Application/Usecases/EditRenterUsecase.php
28 ./app/Features/Renters/Application/Usecases/ShowRenterUsecase.php
25 ./app/Features/Renters/Application/Usecases/UpdateRenterUsecase.php
159 ./app/Features/EstateUtilityServiceInvoices/Presentation/Views/edit.blade.php
144 ./app/Features/EstateUtilityServiceInvoices/Presentation/Views/create.blade.php
127 ./app/Features/EstateUtilityServiceInvoices/Presentation/Http/Controllers/EstateUtilityServiceInvoiceController.php
22 ./app/Features/EstateUtilityServiceInvoices/Presentation/Http/Presenters/ViewEstateUtilityServiceInvoiceFilePresenter.php
52 ./app/Features/EstateUtilityServiceInvoices/Presentation/Http/Presenters/CreateEstateUtilityServiceInvoicePresenter.php
33 ./app/Features/EstateUtilityServiceInvoices/Presentation/Http/Presenters/DestroyEstateUtilityServiceInvoicePresenter.php
22 ./app/Features/EstateUtilityServiceInvoices/Presentation/Http/Presenters/DownloadEstateUtilityServiceInvoiceFilePresenter.php
41 ./app/Features/EstateUtilityServiceInvoices/Presentation/Http/Presenters/UpdateEstateUtilityServiceInvoicePresenter.php
49 ./app/Features/EstateUtilityServiceInvoices/Presentation/Http/Presenters/StoreEstateUtilityServiceInvoicePresenter.php
50 ./app/Features/EstateUtilityServiceInvoices/Presentation/Http/Presenters/EditEstateUtilityServiceInvoicePresenter.php
54 ./app/Features/EstateUtilityServiceInvoices/Presentation/Http/Requests/StoreEstateUtilityServiceInvoiceRequest.php
53 ./app/Features/EstateUtilityServiceInvoices/Presentation/Http/Requests/UpdateEstateUtilityServiceInvoiceRequest.php
45 ./app/Features/EstateUtilityServiceInvoices/Infrastructure/Providers/EstateUtilityServiceInvoiceServiceProvider.php
9 ./app/Features/EstateUtilityServiceInvoices/Application/Outputs/DownloadEstateUtilityServiceInvoiceFileOutput.php
11 ./app/Features/EstateUtilityServiceInvoices/Application/Outputs/EditEstateUtilityServiceInvoiceOutput.php
8 ./app/Features/EstateUtilityServiceInvoices/Application/Outputs/DestroyEstateUtilityServiceInvoiceOutput.php
11 ./app/Features/EstateUtilityServiceInvoices/Application/Outputs/CreateEstateUtilityServiceInvoiceOutput.php
10 ./app/Features/EstateUtilityServiceInvoices/Application/Outputs/UpdateEstateUtilityServiceInvoiceOutput.php
11 ./app/Features/EstateUtilityServiceInvoices/Application/Outputs/StoreEstateUtilityServiceInvoiceOutput.php
14 ./app/Features/EstateUtilityServiceInvoices/Application/Contracts/UpdateEstateUtilityServiceInvoiceContract.php
8 ./app/Features/EstateUtilityServiceInvoices/Application/Contracts/DestroyEstateUtilityServiceInvoiceContract.php
11 ./app/Features/EstateUtilityServiceInvoices/Application/Contracts/StoreEstateUtilityServiceInvoiceContract.php
8 ./app/Features/EstateUtilityServiceInvoices/Application/Contracts/EditEstateUtilityServiceInvoiceContract.php
9 ./app/Features/EstateUtilityServiceInvoices/Application/Contracts/DownloadEstateUtilityServiceInvoiceFileContract.php
9 ./app/Features/EstateUtilityServiceInvoices/Application/Contracts/CreateEstateUtilityServiceInvoiceContract.php
28 ./app/Features/EstateUtilityServiceInvoices/Application/Usecases/DownloadEstateUtilityServiceInvoiceFileUsecase.php
44 ./app/Features/EstateUtilityServiceInvoices/Application/Usecases/UpdateEstateUtilityServiceInvoiceUsecase.php
28 ./app/Features/EstateUtilityServiceInvoices/Application/Usecases/CreateEstateUtilityServiceInvoiceUsecase.php
50 ./app/Features/EstateUtilityServiceInvoices/Application/Usecases/StoreEstateUtilityServiceInvoiceUsecase.php
39 ./app/Features/EstateUtilityServiceInvoices/Application/Usecases/DestroyEstateUtilityServiceInvoiceUsecase.php
29 ./app/Features/EstateUtilityServiceInvoices/Application/Usecases/EditEstateUtilityServiceInvoiceUsecase.php
31 ./app/Features/Settings/Presentation/Views/index.blade.php
16 ./app/Features/Settings/Presentation/Http/Controllers/SettingController.php
24 ./app/Features/Settings/Infrastructure/Providers/SettingServiceProvider.php
11 ./app/Features/Owners/Domain/ValueObjects/OwnerEntitiesWithPagination.php
64 ./app/Features/Owners/Presentation/API/Controllers/OwnerController.php
19 ./app/Features/Owners/Presentation/API/Presenters/DestroyOwnerPresenter.php
45 ./app/Features/Owners/Presentation/API/Presenters/ShowOwnerPresenter.php
36 ./app/Features/Owners/Presentation/API/Presenters/ShowOwnersPaginatePresenter.php
23 ./app/Features/Owners/Presentation/API/Presenters/EditOwnerPresenter.php
20 ./app/Features/Owners/Presentation/API/Presenters/StoreOwnerPresenter.php
42 ./app/Features/Owners/Presentation/API/Presenters/CreateOwnerPresenter.php
19 ./app/Features/Owners/Presentation/API/Presenters/UpdateOwnerPresenter.php
168 ./app/Features/Owners/Presentation/Views/index.blade.php
183 ./app/Features/Owners/Presentation/Views/edit.blade.php
176 ./app/Features/Owners/Presentation/Views/show.blade.php
172 ./app/Features/Owners/Presentation/Views/create.blade.php
120 ./app/Features/Owners/Presentation/Http/Controllers/OwnerController.php
31 ./app/Features/Owners/Presentation/Http/Presenters/DestroyOwnerPresenter.php
53 ./app/Features/Owners/Presentation/Http/Presenters/ShowOwnerPresenter.php
61 ./app/Features/Owners/Presentation/Http/Presenters/ShowOwnersPaginatePresenter.php
71 ./app/Features/Owners/Presentation/Http/Presenters/EditOwnerPresenter.php
37 ./app/Features/Owners/Presentation/Http/Presenters/StoreOwnerPresenter.php
46 ./app/Features/Owners/Presentation/Http/Presenters/UpdateOwnerPresenter.php
66 ./app/Features/Owners/Presentation/Http/Requests/UpdateOwnerRequest.php
71 ./app/Features/Owners/Presentation/Http/Requests/StoreOwnerRequest.php
48 ./app/Features/Owners/Infrastructure/Providers/OwnerServiceProvider.php
18 ./app/Features/Owners/Application/Outputs/EditOwnerOutput.php
18 ./app/Features/Owners/Application/Outputs/ShowOwnersPaginationOutput.php
8 ./app/Features/Owners/Application/Outputs/DestroyOwnerOutput.php
14 ./app/Features/Owners/Application/Outputs/CreateOwnerOutput.php
8 ./app/Features/Owners/Application/Outputs/UpdateOwnerOutput.php
10 ./app/Features/Owners/Application/Outputs/StoreOwnerOutput.php
11 ./app/Features/Owners/Application/Outputs/ShowOwnerOutput.php
9 ./app/Features/Owners/Application/Contracts/DestroyOwnerContract.php
8 ./app/Features/Owners/Application/Contracts/EditOwnerContract.php
15 ./app/Features/Owners/Application/Contracts/StoreOwnerContract.php
11 ./app/Features/Owners/Application/Contracts/ShowOwnerContract.php
8 ./app/Features/Owners/Application/Contracts/CreateOwnerContract.php
12 ./app/Features/Owners/Application/Contracts/ShowOwnersPaginationContract.php
13 ./app/Features/Owners/Application/Contracts/UpdateOwnerContract.php
39 ./app/Features/Owners/Application/Usecases/StoreOwnerUsecase.php
23 ./app/Features/Owners/Application/Usecases/DestroyOwnerUsecase.php
29 ./app/Features/Owners/Application/Usecases/ShowOwnerUsecase.php
36 ./app/Features/Owners/Application/Usecases/UpdateOwnerUsecase.php
26 ./app/Features/Owners/Application/Usecases/CreateOwnerUsecase.php
20 ./app/Features/Owners/Application/Usecases/ShowPaginateOwnerUsecase.php
33 ./app/Features/Owners/Application/Usecases/EditOwnerUsecase.php
151 ./app/Features/UnitUtilityServices/Presentation/Views/index.blade.php
156 ./app/Features/UnitUtilityServices/Presentation/Views/edit.blade.php
127 ./app/Features/UnitUtilityServices/Presentation/Views/show.blade.php
144 ./app/Features/UnitUtilityServices/Presentation/Views/create.blade.php
98 ./app/Features/UnitUtilityServices/Presentation/Http/Controllers/UnitUtilityServiceController.php
49 ./app/Features/UnitUtilityServices/Presentation/Http/Presenters/UpdateUnitUtilityServicePresenter.php
64 ./app/Features/UnitUtilityServices/Presentation/Http/Presenters/EditUnitUtilityServicePresenter.php
38 ./app/Features/UnitUtilityServices/Presentation/Http/Presenters/StoreUnitUtilityServicesPresenter.php
61 ./app/Features/UnitUtilityServices/Presentation/Http/Presenters/ShowAllUnitUtilityServicePresenter.php
40 ./app/Features/UnitUtilityServices/Presentation/Http/Presenters/DestroyUnitUtilityServicePresenter.php
40 ./app/Features/UnitUtilityServices/Presentation/Http/Presenters/CreateUnitUtilityServicePresenter.php
51 ./app/Features/UnitUtilityServices/Presentation/Http/Presenters/ShowUnitUtilityServicePresenter.php
50 ./app/Features/UnitUtilityServices/Presentation/Http/Requests/UpdateUnitUtilityServiceRequest.php
45 ./app/Features/UnitUtilityServices/Presentation/Http/Requests/StoreUnitUtilityServiceRequest.php
48 ./app/Features/UnitUtilityServices/Infrastructure/Providers/UnitUtilityServicesServiceProvider.php
13 ./app/Features/UnitUtilityServices/Application/Outputs/CreateUnitUtilityServiceOutput.php
17 ./app/Features/UnitUtilityServices/Application/Outputs/ShowAllUnitUtilityServicesOutput.php
12 ./app/Features/UnitUtilityServices/Application/Outputs/ShowUnitUtilityServiceOutput.php
10 ./app/Features/UnitUtilityServices/Application/Outputs/StoreUnitUtilityServiceOutput.php
10 ./app/Features/UnitUtilityServices/Application/Outputs/EditUnitUtilityServiceOutput.php
7 ./app/Features/UnitUtilityServices/Application/Outputs/UpdateUnitUtilityServiceOutput.php
8 ./app/Features/UnitUtilityServices/Application/Outputs/DestroyUnitUtilityServiceOutput.php
10 ./app/Features/UnitUtilityServices/Application/Contracts/StoreUnitUtilityServiceContract.php
12 ./app/Features/UnitUtilityServices/Application/Contracts/EditUnitUtilityServiceContract.php
9 ./app/Features/UnitUtilityServices/Application/Contracts/DestroyUnitUtilityServiceContract.php
8 ./app/Features/UnitUtilityServices/Application/Contracts/CreateUnitUtilityServiceContract.php
9 ./app/Features/UnitUtilityServices/Application/Contracts/ShowUnitUtilityServiceContract.php
13 ./app/Features/UnitUtilityServices/Application/Contracts/UpdateUnitUtilityServiceContract.php
8 ./app/Features/UnitUtilityServices/Application/Contracts/ShowAllUnitUtilityServiceContract.php
28 ./app/Features/UnitUtilityServices/Application/Usecases/EditUnitUtilityServiceUsecase.php
27 ./app/Features/UnitUtilityServices/Application/Usecases/UpdateUnitUtilityServiceUsecase.php
29 ./app/Features/UnitUtilityServices/Application/Usecases/CreateUnitUtilityServiceUsecase.php
36 ./app/Features/UnitUtilityServices/Application/Usecases/ShowUnitUtilityServiceUsecase.php
24 ./app/Features/UnitUtilityServices/Application/Usecases/DestroyUnitUtilityServiceUsecase.php
29 ./app/Features/UnitUtilityServices/Application/Usecases/StroreUnitUtilityServicesUsecase.php
34 ./app/Features/UnitUtilityServices/Application/Usecases/ShowAllUnitUtilityServiceUsecase.php
193 ./app/Features/EstateMaintenanceExpenses/Presentation/Views/index.blade.php
150 ./app/Features/EstateMaintenanceExpenses/Presentation/Views/edit.blade.php
115 ./app/Features/EstateMaintenanceExpenses/Presentation/Views/show.blade.php
132 ./app/Features/EstateMaintenanceExpenses/Presentation/Views/create.blade.php
106 ./app/Features/EstateMaintenanceExpenses/Presentation/Http/Controllers/EstateMaintenanceExpensesController.php
39 ./app/Features/EstateMaintenanceExpenses/Presentation/Http/Presenters/DestroyEstateMaintenanceExpensesPresenter.php
38 ./app/Features/EstateMaintenanceExpenses/Presentation/Http/Presenters/UpdateEstateMaintenanceExpensesPresenter.php
50 ./app/Features/EstateMaintenanceExpenses/Presentation/Http/Presenters/CreateEstateMaintenanceExpensesPresenter.php
56 ./app/Features/EstateMaintenanceExpenses/Presentation/Http/Presenters/ShowEstateMaintenanceExpensesPresenter.php
63 ./app/Features/EstateMaintenanceExpenses/Presentation/Http/Presenters/ShowAllEstateMaintenanceExpensesPresenter.php
38 ./app/Features/EstateMaintenanceExpenses/Presentation/Http/Presenters/StoreEstateMaintenanceExpensesPresenter.php
61 ./app/Features/EstateMaintenanceExpenses/Presentation/Http/Presenters/EditEstateMaintenanceExpensesPresenter.php
44 ./app/Features/EstateMaintenanceExpenses/Presentation/Http/Requests/UpdateEstateMaintenanceExpensesRequest.php
44 ./app/Features/EstateMaintenanceExpenses/Presentation/Http/Requests/StoreEstateMaintenanceExpensesRequest.php
47 ./app/Features/EstateMaintenanceExpenses/Infrastructure/Providers/EstateMaintenanceExpensesServiceProvider.php
10 ./app/Features/EstateMaintenanceExpenses/Application/Outputs/EditEstateMaintenanceExpensesOutput.php
14 ./app/Features/EstateMaintenanceExpenses/Application/Outputs/StoreEstateMaintenanceExpensesOutput.php
11 ./app/Features/EstateMaintenanceExpenses/Application/Outputs/CreateEstateMaintenanceExpensesOutput.php
10 ./app/Features/EstateMaintenanceExpenses/Application/Outputs/ShowEstateMaintenanceExpensesOutput.php
8 ./app/Features/EstateMaintenanceExpenses/Application/Outputs/DestroyEstateMaintenanceExpensesOutput.php
18 ./app/Features/EstateMaintenanceExpenses/Application/Outputs/ShowAllEstateMaintenanceExpensesOutput.php
8 ./app/Features/EstateMaintenanceExpenses/Application/Outputs/UpdateEstateMaintenanceExpensesOutput.php
8 ./app/Features/EstateMaintenanceExpenses/Application/Contracts/DestroyEstateMaintenanceExpensesContract.php
8 ./app/Features/EstateMaintenanceExpenses/Application/Contracts/ShowEstateMaintenanceExpensesContract.php
9 ./app/Features/EstateMaintenanceExpenses/Application/Contracts/ShowAllEstateMaintenanceExpensesContract.php
10 ./app/Features/EstateMaintenanceExpenses/Application/Contracts/StoreEstateMaintenanceExpensesContract.php
9 ./app/Features/EstateMaintenanceExpenses/Application/Contracts/UpdateEstateMaintenanceExpensesContract.php
8 ./app/Features/EstateMaintenanceExpenses/Application/Contracts/EditEstateMaintenanceExpensesContract.php
9 ./app/Features/EstateMaintenanceExpenses/Application/Contracts/CreateEstateMaintenanceExpensesContract.php
28 ./app/Features/EstateMaintenanceExpenses/Application/Usecases/StoreEstateMaintenanceExpensesUsecase.php
23 ./app/Features/EstateMaintenanceExpenses/Application/Usecases/ShowEstateMaintenanceExpensesUsecase.php
32 ./app/Features/EstateMaintenanceExpenses/Application/Usecases/ShowAllEstateMaintenanceExpensesUsecase.php
24 ./app/Features/EstateMaintenanceExpenses/Application/Usecases/CreateEstateMaintenanceExpensesUsecase.php
31 ./app/Features/EstateMaintenanceExpenses/Application/Usecases/UpdateEstateMaintenanceExpensesUsecase.php
28 ./app/Features/EstateMaintenanceExpenses/Application/Usecases/EditEstateMaintenanceExpensesUsecase.php
33 ./app/Features/EstateMaintenanceExpenses/Application/Usecases/DestroyEstateMaintenanceExpensesUsecase.php
11 ./app/Features/Units/Domain/ValueObjects/UnitEntitiesWithPagination.php
198 ./app/Features/Units/Presentation/Views/index.blade.php
151 ./app/Features/Units/Presentation/Views/edit.blade.php
182 ./app/Features/Units/Presentation/Views/show.blade.php
142 ./app/Features/Units/Presentation/Views/create.blade.php
101 ./app/Features/Units/Presentation/Http/Controllers/UnitController.php
57 ./app/Features/Units/Presentation/Http/Presenters/ShowUnitPresenter.php
38 ./app/Features/Units/Presentation/Http/Presenters/CreateUnitPresenter.php
41 ./app/Features/Units/Presentation/Http/Presenters/StoreUnitPresenter.php
37 ./app/Features/Units/Presentation/Http/Presenters/DestroyUnitPresenter.php
63 ./app/Features/Units/Presentation/Http/Presenters/EditUnitPresenter.php
41 ./app/Features/Units/Presentation/Http/Presenters/UpdateUnitPresenter.php
65 ./app/Features/Units/Presentation/Http/Presenters/ShowUnitsPaginatePresenter.php
59 ./app/Features/Units/Presentation/Http/Requests/StoreUnitRequest.php
61 ./app/Features/Units/Presentation/Http/Requests/UpdateUnitRequest.php
47 ./app/Features/Units/Infrastructure/Providers/UnitServiceProvider.php
18 ./app/Features/Units/Application/DTOs/UnitFormDTO.php
12 ./app/Features/Units/Application/Ouputs/EditUnitOutput.php
10 ./app/Features/Units/Application/Ouputs/StoreUnitOutput.php
12 ./app/Features/Units/Application/Ouputs/ShowUnitOutput.php
10 ./app/Features/Units/Application/Ouputs/CreateUnitOutput.php
11 ./app/Features/Units/Application/Ouputs/UpdateUnitOutput.php
9 ./app/Features/Units/Application/Ouputs/DestroyUnitOutput.php
17 ./app/Features/Units/Application/Ouputs/ShowUnitsPaginationOutput.php
10 ./app/Features/Units/Application/Contracts/UpdateUnitContract.php
10 ./app/Features/Units/Application/Contracts/DestroyUnitContract.php
12 ./app/Features/Units/Application/Contracts/EditUnitContract.php
12 ./app/Features/Units/Application/Contracts/ShowUnitsPaginationContract.php
13 ./app/Features/Units/Application/Contracts/StoreUnitContract.php
11 ./app/Features/Units/Application/Contracts/ShowUnitContract.php
8 ./app/Features/Units/Application/Contracts/CreateUnitContract.php
40 ./app/Features/Units/Application/Usecases/EditUnitUsecase.php
33 ./app/Features/Units/Application/Usecases/CreateUnitUsecase.php
30 ./app/Features/Units/Application/Usecases/StoreUnitUsecase.php
32 ./app/Features/Units/Application/Usecases/ShowPaginateUnitUsecase.php
26 ./app/Features/Units/Application/Usecases/UpdateUnitUsecase.php
25 ./app/Features/Units/Application/Usecases/DestroyUnitUsecase.php
25 ./app/Features/Units/Application/Usecases/ShowUnitUsecase.php
220 ./app/Features/UnitOwnerships/Presentation/Views/create.blade.php
64 ./app/Features/UnitOwnerships/Presentation/Http/Controllers/UnitOwnershipController.php
31 ./app/Features/UnitOwnerships/Presentation/Http/Presenters/DestroyUnitOwnershipPresenter.php
44 ./app/Features/UnitOwnerships/Presentation/Http/Presenters/CreateUnitOwnershipPresenter.php
41 ./app/Features/UnitOwnerships/Presentation/Http/Presenters/StoreUnitOwnershipPresenter.php
37 ./app/Features/UnitOwnerships/Presentation/Http/Requests/StoreUnitOwnershipRequest.php
39 ./app/Features/UnitOwnerships/Infrastructure/Providers/UnitOwnershipProvider.php
13 ./app/Features/UnitOwnerships/Application/DTOs/OwnershipByOwnersFormDTO.php
13 ./app/Features/UnitOwnerships/Application/DTOs/OwnershipByOwnersGroupsDTO.php
7 ./app/Features/UnitOwnerships/Application/Outputs/DestroyUnitOwnershipOutput.php
14 ./app/Features/UnitOwnerships/Application/Outputs/StoreUnitOwnershipsOutput.php
16 ./app/Features/UnitOwnerships/Application/Outputs/CreateUnitOwnershipOutput.php
12 ./app/Features/UnitOwnerships/Application/Contracts/CreateUnitOwnershipContract.php
14 ./app/Features/UnitOwnerships/Application/Contracts/StoreUnitOwnershipsByOwnersContract.php
20 ./app/Features/UnitOwnerships/Application/Contracts/StoreUnitOwnershipsByOwnerGoupsContract.php
12 ./app/Features/UnitOwnerships/Application/Contracts/DestroyUnitOwnershipContract.php
38 ./app/Features/UnitOwnerships/Application/Usecases/CreateUnitOwnershipUsecase.php
30 ./app/Features/UnitOwnerships/Application/Usecases/StoreUnitOwnershipsByOwnersUsecase.php
22 ./app/Features/UnitOwnerships/Application/Usecases/DestroyUnitOwnershipUsecase.php
31 ./app/Features/UnitOwnerships/Application/Usecases/StoreUnitOwnershipsByOwnerGoupsUsecase.php
12 ./app/Features/Estates/Domain/ValueObjects/EstateEntitiesWithPagination.php
157 ./app/Features/Estates/Presentation/Views/index.blade.php
97 ./app/Features/Estates/Presentation/Views/show.blade.php
92 ./app/Features/Estates/Presentation/Views/create.blade.php
71 ./app/Features/Estates/Presentation/Http/Controllers/EstateController.php
41 ./app/Features/Estates/Presentation/Http/Presenters/ShowEstaetsPaginatePresenter.php
37 ./app/Features/Estates/Presentation/Http/Presenters/StoreEstatePresenter.php
44 ./app/Features/Estates/Presentation/Http/Presenters/ShowEstatePresenter.php
52 ./app/Features/Estates/Presentation/Http/Requests/StoreEstateRequest.php
34 ./app/Features/Estates/Infrastructure/Providers/EstateServiceProvider.php
11 ./app/Features/Estates/Application/Outputs/ShowEstateOutput.php
9 ./app/Features/Estates/Application/Outputs/StoreEstateOutput.php
11 ./app/Features/Estates/Application/Outputs/ShowEstatesPaginationOutput.php
15 ./app/Features/Estates/Application/Contracts/StoreEstateContract.php
10 ./app/Features/Estates/Application/Contracts/ShowEstateContract.php
8 ./app/Features/Estates/Application/Contracts/ShowEstatesPaginationContract.php
25 ./app/Features/Estates/Application/Usecases/ShowPaginateEstateUsecase.php
62 ./app/Features/Estates/Application/Usecases/StoreEstateUsecase.php
31 ./app/Features/Estates/Application/Usecases/ShowEstateUsecase.php
10 ./app/Features/UnitContracts/Domain/ValueObjects/UnitContractEntitiesWithPagination.php
220 ./app/Features/UnitContracts/Presentation/Views/index.blade.php
198 ./app/Features/UnitContracts/Presentation/Views/edit.blade.php
161 ./app/Features/UnitContracts/Presentation/Views/show.blade.php
186 ./app/Features/UnitContracts/Presentation/Views/create.blade.php
107 ./app/Features/UnitContracts/Presentation/Http/Controllers/UnitContractController.php
67 ./app/Features/UnitContracts/Presentation/Http/Presenters/EditUnitContractPresenter.php
43 ./app/Features/UnitContracts/Presentation/Http/Presenters/DestroyUnitContractPresenter.php
54 ./app/Features/UnitContracts/Presentation/Http/Presenters/CreateUnitContractContractPresenter.php
44 ./app/Features/UnitContracts/Presentation/Http/Presenters/StoreUnitContractPresenter.php
58 ./app/Features/UnitContracts/Presentation/Http/Presenters/ShowUnitContractsPaginationPresenter.php
58 ./app/Features/UnitContracts/Presentation/Http/Presenters/ShowUnitContractPresenter.php
52 ./app/Features/UnitContracts/Presentation/Http/Presenters/UpdateUnitContractPresenter.php
38 ./app/Features/UnitContracts/Presentation/Http/Requests/Rules/UnitContractDateIntersectionRule.php
75 ./app/Features/UnitContracts/Presentation/Http/Requests/StoreUnitContractRequest.php
75 ./app/Features/UnitContracts/Presentation/Http/Requests/UpdateUnitContractRequest.php
47 ./app/Features/UnitContracts/Infrastructure/Providers/UnitContractServiceProvider.php
17 ./app/Features/UnitContracts/Application/Ouputs/EditUnitContractOutput.php
10 ./app/Features/UnitContracts/Application/Ouputs/DestroyUnitContractOutput.php
9 ./app/Features/UnitContracts/Application/Ouputs/UpdateUnitContractOutput.php
12 ./app/Features/UnitContracts/Application/Ouputs/ShowUnitContractOutput.php
17 ./app/Features/UnitContracts/Application/Ouputs/CreateUnitContractContractOutput.php
12 ./app/Features/UnitContracts/Application/Ouputs/ShowUnitContractsPaginationOutput.php
10 ./app/Features/UnitContracts/Application/Ouputs/StoreUnitContractOutput.php
10 ./app/Features/UnitContracts/Application/Contracts/StoreUnitContractContract.php
9 ./app/Features/UnitContracts/Application/Contracts/DestroyUnitContractContract.php
9 ./app/Features/UnitContracts/Application/Contracts/ShowUnitContractContract.php
9 ./app/Features/UnitContracts/Application/Contracts/CreateUnitContractContract.php
9 ./app/Features/UnitContracts/Application/Contracts/EditUnitContractContract.php
10 ./app/Features/UnitContracts/Application/Contracts/UpdateUnitContractContract.php
9 ./app/Features/UnitContracts/Application/Contracts/ShowUnitContractsPaginationContract.php
34 ./app/Features/UnitContracts/Application/Usecases/ShowUnitContractsPaginationUsecase.php
23 ./app/Features/UnitContracts/Application/Usecases/UpdateUnitContractUsecase.php
35 ./app/Features/UnitContracts/Application/Usecases/EditUnitContractUsecase.php
23 ./app/Features/UnitContracts/Application/Usecases/DestroyUnitContractUsecase.php
34 ./app/Features/UnitContracts/Application/Usecases/CreateUnitContractContractUsecase.php
24 ./app/Features/UnitContracts/Application/Usecases/ShowUnitContractUsecase.php
24 ./app/Features/UnitContracts/Application/Usecases/StoreUnitContractUsecase.php
5 ./app/Features/Queries/Presentation/Views/index.blade.php
13 ./app/Features/Queries/Presentation/Http/Controllers/QueryContoller.php
26 ./app/Features/Queries/Infrastructure/Providers/QueryServiceProvider.php
11 ./app/Features/OwnerGroups/Domain/ValueObjects/OwnerGroupEntitiesWithPagination.php
154 ./app/Features/OwnerGroups/Presentation/Views/index.blade.php
80 ./app/Features/OwnerGroups/Presentation/Views/edit.blade.php
144 ./app/Features/OwnerGroups/Presentation/Views/show.blade.php
67 ./app/Features/OwnerGroups/Presentation/Views/create.blade.php
97 ./app/Features/OwnerGroups/Presentation/Http/Controllers/OwnerGroupController.php
47 ./app/Features/OwnerGroups/Presentation/Http/Presenters/UpdateOwnerGroupPresenter.php
52 ./app/Features/OwnerGroups/Presentation/Http/Presenters/ShowOwnerGroupPaginatePresenter.php
25 ./app/Features/OwnerGroups/Presentation/Http/Presenters/DestroyOwnerGroupPresenter.php
57 ./app/Features/OwnerGroups/Presentation/Http/Presenters/EditOwnerGroupPresenter.php
28 ./app/Features/OwnerGroups/Presentation/Http/Presenters/UnlinkOwnerFromGroupPresneter.php
54 ./app/Features/OwnerGroups/Presentation/Http/Presenters/ShowOwnerGroupPresenter.php
36 ./app/Features/OwnerGroups/Presentation/Http/Presenters/StoreOwnerGroupPresenter.php
47 ./app/Features/OwnerGroups/Presentation/Http/Requests/UpdateOwnerGroupRequest.php
47 ./app/Features/OwnerGroups/Presentation/Http/Requests/StoreOwnerGroupRequest.php
46 ./app/Features/OwnerGroups/Infrastructure/Providers/OwnerGroupServiceProvider.php
9 ./app/Features/OwnerGroups/Application/Outputs/StoreOwnerGroupOutput.php
11 ./app/Features/OwnerGroups/Application/Outputs/ShowOwnerGroupOutput.php
7 ./app/Features/OwnerGroups/Application/Outputs/UnlinkOwnerFromGroupOutput.php
9 ./app/Features/OwnerGroups/Application/Outputs/ShowOwnerGroupsPaginationOutput.php
9 ./app/Features/OwnerGroups/Application/Outputs/UpdateOwnerGroupOutput.php
7 ./app/Features/OwnerGroups/Application/Outputs/DestroyOwnerGroupOutput.php
10 ./app/Features/OwnerGroups/Application/Outputs/EditOwnerGroupsOutput.php
9 ./app/Features/OwnerGroups/Application/Contracts/UnlinkOwnerFromGroupContract.php
9 ./app/Features/OwnerGroups/Application/Contracts/ShowOwnerGroupContract.php
12 ./app/Features/OwnerGroups/Application/Contracts/EditOwnerGroupContract.php
8 ./app/Features/OwnerGroups/Application/Contracts/ShowOwnerGroupsPaginationContract.php
10 ./app/Features/OwnerGroups/Application/Contracts/UpdateOwnerGroupContrat.php
8 ./app/Features/OwnerGroups/Application/Contracts/DestroyOwnerGroupContract.php
10 ./app/Features/OwnerGroups/Application/Contracts/StoreOwnerGroupContract.php
22 ./app/Features/OwnerGroups/Application/Usecases/ShowPaginateOwnerGroupUsecase.php
28 ./app/Features/OwnerGroups/Application/Usecases/UpdateOwnerGroupUsecase.php
25 ./app/Features/OwnerGroups/Application/Usecases/EditOwnerGroupUsecase.php
22 ./app/Features/OwnerGroups/Application/Usecases/UnlinkOwnerFromGroupUsecase.php
25 ./app/Features/OwnerGroups/Application/Usecases/DestroyOwnerGroupUsecase.php
22 ./app/Features/OwnerGroups/Application/Usecases/StoreOwnerGroupUsecase.php
28 ./app/Features/OwnerGroups/Application/Usecases/ShowOwnerGroupUsecase.php
12 ./app/Features/EstateDocuments/Domain/ValueObjects/EstateDocumentEntitiesWithPagination.php
209 ./app/Features/EstateDocuments/Presentation/Views/index.blade.php
136 ./app/Features/EstateDocuments/Presentation/Views/edit.blade.php
112 ./app/Features/EstateDocuments/Presentation/Views/show.blade.php
115 ./app/Features/EstateDocuments/Presentation/Views/create.blade.php
140 ./app/Features/EstateDocuments/Presentation/Http/Controllers/EstateDocumentController.php
60 ./app/Features/EstateDocuments/Presentation/Http/Presenters/ShowEstateDocumentPresenter.php
37 ./app/Features/EstateDocuments/Presentation/Http/Presenters/ViewEstateDocumentFilePresenter.php
23 ./app/Features/EstateDocuments/Presentation/Http/Presenters/DownloadEstateDocumentFilePresenter.php
37 ./app/Features/EstateDocuments/Presentation/Http/Presenters/DestroyEstateDocumentPresenter.php
50 ./app/Features/EstateDocuments/Presentation/Http/Presenters/UpdateEstateDocumentPresenter.php
45 ./app/Features/EstateDocuments/Presentation/Http/Presenters/CreateEstateDocumentPresenter.php
64 ./app/Features/EstateDocuments/Presentation/Http/Presenters/ShowEstateDocumentsPaginatePresenter.php
54 ./app/Features/EstateDocuments/Presentation/Http/Presenters/EditEstateDocumentPresenter.php
36 ./app/Features/EstateDocuments/Presentation/Http/Presenters/StoreEstateDocumentPresenter.php
42 ./app/Features/EstateDocuments/Presentation/Http/Requests/UpdateEstateDocumentRequest.php
41 ./app/Features/EstateDocuments/Presentation/Http/Requests/StoreEstateDocumentRequest.php
50 ./app/Features/EstateDocuments/Infrastructure/Providers/EstateDocumentServiceProvider.php
10 ./app/Features/EstateDocuments/Application/Outputs/EditEstateDocumentOutput.php
8 ./app/Features/EstateDocuments/Application/Outputs/DownloadEstateDocumentFileOutput.php
7 ./app/Features/EstateDocuments/Application/Outputs/UpdateEstateDocumentOutput.php
9 ./app/Features/EstateDocuments/Application/Outputs/StoreEstateDocumentOutput.php
11 ./app/Features/EstateDocuments/Application/Outputs/ShowEstateDocumentOutput.php
11 ./app/Features/EstateDocuments/Application/Outputs/CreateEstateDocumentOutput.php
8 ./app/Features/EstateDocuments/Application/Outputs/DestroyEstateDocumentOutput.php
19 ./app/Features/EstateDocuments/Application/Outputs/ShowEstateDocumentsPaginationOutput.php
12 ./app/Features/EstateDocuments/Application/Contracts/DownloadEstateDocumentFileContract.php
15 ./app/Features/EstateDocuments/Application/Contracts/UpdateEstateDocumentContract.php
12 ./app/Features/EstateDocuments/Application/Contracts/CreateEstateDocumentContract.php
12 ./app/Features/EstateDocuments/Application/Contracts/DestroyEstateDocumentContract.php
14 ./app/Features/EstateDocuments/Application/Contracts/StoreEstateDocumentContract.php
12 ./app/Features/EstateDocuments/Application/Contracts/ShowEstateDocumentsPaginationContract.php
12 ./app/Features/EstateDocuments/Application/Contracts/EditEstateDocumentContract.php
13 ./app/Features/EstateDocuments/Application/Contracts/ShowEstateDocumentContract.php
29 ./app/Features/EstateDocuments/Application/Usecases/EditEstateDocumentUsecase.php
43 ./app/Features/EstateDocuments/Application/Usecases/UpdateEstateDocumentUsecase.php
28 ./app/Features/EstateDocuments/Application/Usecases/DownloadEstateDocumentFileUsecase.php
29 ./app/Features/EstateDocuments/Application/Usecases/CreateEstateDocumentUsecase.php
45 ./app/Features/EstateDocuments/Application/Usecases/StoreEstateDocumentUsecase.php
32 ./app/Features/EstateDocuments/Application/Usecases/ShowPaginateEstateDocumentUsecase.php
28 ./app/Features/EstateDocuments/Application/Usecases/ShowEstateDocumentsUsecase.php
37 ./app/Features/EstateDocuments/Application/Usecases/DestroyEstateDocumentUsecase.php
187 ./app/Features/RentInvoices/Presentation/Views/index.blade.php
158 ./app/Features/RentInvoices/Presentation/Views/show.blade.php
174 ./app/Features/RentInvoices/Presentation/Views/create.blade.php
92 ./app/Features/RentInvoices/Presentation/Http/Controllers/RentInvoiceController.php
49 ./app/Features/RentInvoices/Presentation/Http/Presenters/ShowRentInvoicePresenter.php
24 ./app/Features/RentInvoices/Presentation/Http/Presenters/EditRentInvoicePresenter.php
45 ./app/Features/RentInvoices/Presentation/Http/Presenters/CreateRentInvoicePresenter.php
45 ./app/Features/RentInvoices/Presentation/Http/Presenters/ShowAllRentInvoicePresenter.php
45 ./app/Features/RentInvoices/Presentation/Http/Presenters/StoreRentInvoicePresenter.php
46 ./app/Features/RentInvoices/Presentation/Http/Requests/StoreRentInvoiceRequest.php
38 ./app/Features/RentInvoices/Infrastructure/Providers/RentInvoiceServiceProvider.php
14 ./app/Features/RentInvoices/Application/Outputs/EditRentInvoiceOutput.php
12 ./app/Features/RentInvoices/Application/Outputs/CreateRentInvoiceOutput.php
12 ./app/Features/RentInvoices/Application/Outputs/StoreRentInvoiceOutput.php
19 ./app/Features/RentInvoices/Application/Outputs/ShowAllRentInvoicesOutput.php
13 ./app/Features/RentInvoices/Application/Outputs/ShowRentInvoiceOutput.php
13 ./app/Features/RentInvoices/Application/Usecase/EditRentInvoiceUsecase.php
25 ./app/Features/RentInvoices/Application/Usecase/CreateRentInvoiceUsecase.php
33 ./app/Features/RentInvoices/Application/Usecase/StoreRentInvoiceUsecase.php
33 ./app/Features/RentInvoices/Application/Usecase/ShowAllRentInvoicesUsecase.php
28 ./app/Features/RentInvoices/Application/Usecase/ShowRentInvoiceUsecase.php
10 ./app/Features/RentInvoices/Application/Contracts/ShowRentInvoiceContract.php
10 ./app/Features/RentInvoices/Application/Contracts/CreateRentInvoiceContract.php
10 ./app/Features/RentInvoices/Application/Contracts/EditRentInvoiceContract.php
10 ./app/Features/RentInvoices/Application/Contracts/ShowAllRentInvoicesContract.php
11 ./app/Features/RentInvoices/Application/Contracts/StoreRentInvoiceContract.php
26 ./app/Shared/Domain/Enum/Transaction/TransactionDirection.php
26 ./app/Shared/Domain/Enum/Renter/RenterIdentityType.php
23 ./app/Shared/Domain/Enum/Unit/UnitUtilityServiceType.php
26 ./app/Shared/Domain/Enum/Unit/UnitContractType.php
30 ./app/Shared/Domain/Enum/Unit/UnitIsEmpty.php
26 ./app/Shared/Domain/Enum/Unit/UnitType.php
27 ./app/Shared/Domain/Enum/Estate/EstateUtilityServiceType.php
34 ./app/Shared/Domain/Traits/EnumUtilities.php
38 ./app/Shared/Domain/Entities/Transaction/TransactionEntity.php
17 ./app/Shared/Domain/Entities/RentsPayment/RentInvoiceEntity.php
63 ./app/Shared/Domain/Entities/Owner/OwnerEntity.php
16 ./app/Shared/Domain/Entities/Owner/OwnerInGroupEntity.php
10 ./app/Shared/Domain/Entities/Owner/OwnerPhoneEntity.php
24 ./app/Shared/Domain/Entities/Owner/OwnerGroupEntity.php
11 ./app/Shared/Domain/Entities/Renter/RenterPhoneEntity.php
25 ./app/Shared/Domain/Entities/Renter/RenterEntity.php
14 ./app/Shared/Domain/Entities/Setting/SettingEntity.php
23 ./app/Shared/Domain/Entities/Unit/UnitUtilityServiceEntity.php
38 ./app/Shared/Domain/Entities/Unit/UnitEntity.php
18 ./app/Shared/Domain/Entities/Unit/UnitOwnershipEntity.php
80 ./app/Shared/Domain/Entities/Unit/UnitContractEntity.php
18 ./app/Shared/Domain/Entities/Estate/EstateUtilityServiceInvoiceEntity.php
40 ./app/Shared/Domain/Entities/Estate/EstateEntity.php
33 ./app/Shared/Domain/Entities/Estate/EstateUtilityServiceEntity.php
31 ./app/Shared/Domain/Entities/Estate/EstateDocumentEntity.php
21 ./app/Shared/Domain/Entities/Estate/EstateMaintenanceExpensesEntity.php
27 ./app/Shared/Domain/Repositories/EstateDocumentRepository.php
27 ./app/Shared/Domain/Repositories/RentInvoiceRepository.php
16 ./app/Shared/Domain/Repositories/UnitOwnershipRepository.php
17 ./app/Shared/Domain/Repositories/EstateUtilityServiceInvoiceRepository.php
11 ./app/Shared/Domain/Repositories/SettingRepository.php
26 ./app/Shared/Domain/Repositories/EstateRepositroy.php
17 ./app/Shared/Domain/Repositories/EstateUtilityServiceRepository.php
24 ./app/Shared/Domain/Repositories/OwnerGroupRepository.php
25 ./app/Shared/Domain/Repositories/RenterRepositroy.php
25 ./app/Shared/Domain/Repositories/OwnerRepository.php
18 ./app/Shared/Domain/Repositories/OwnerInGroupRepository.php
33 ./app/Shared/Domain/Repositories/UnitRepository.php
25 ./app/Shared/Domain/Repositories/UnitUtilityServiceRepository.php
25 ./app/Shared/Domain/Repositories/EstateMaintenanceExpensesRepository.php
18 ./app/Shared/Domain/Repositories/UnitContractRepository.php
22 ./app/Shared/Domain/Repositories/TransactionRepository.php
18 ./app/Shared/Domain/ValueObjects/EntitiesWithPagination.php
58 ./app/Shared/Domain/ValueObjects/Pagination.php
16 ./app/Shared/Domain/Contracts/DateProviderContract.php
33 ./app/Shared/Presentation/API/Controllers/TokenController.php
20 ./app/Shared/Presentation/Views/main-footer-assets.blade.php
331 ./app/Shared/Presentation/Views/main-layout.blade.php
6 ./app/Shared/Presentation/Views/main-header-assets.blade.php
12 ./app/Shared/Presentation/Constants/Messages.php
56 ./app/Shared/Infrastructure/Session/Constants/SessionKeys.php
23 ./app/Shared/Infrastructure/Storage/LaravelStorage.php
39 ./app/Shared/Infrastructure/Storage/LaravelFile.php
78 ./app/Shared/Infrastructure/Utilities/CarbonDateUtility.php
9 ./app/Shared/Infrastructure/Utilities/Helper.php
24 ./app/Shared/Infrastructure/Models/Transaction/Transaction.php
29 ./app/Shared/Infrastructure/Models/Owner/Owner.php
22 ./app/Shared/Infrastructure/Models/Owner/OwnerInGroup.php
18 ./app/Shared/Infrastructure/Models/Owner/OwnerPhone.php
16 ./app/Shared/Infrastructure/Models/Renter/RenterPhone.php
18 ./app/Shared/Infrastructure/Models/Renter/Renter.php
12 ./app/Shared/Infrastructure/Models/Setting/Setting.php
30 ./app/Shared/Infrastructure/Models/Unit/Unit.php
21 ./app/Shared/Infrastructure/Models/Unit/UnitUtilityService.php
36 ./app/Shared/Infrastructure/Models/Unit/UnitContract.php
22 ./app/Shared/Infrastructure/Models/Unit/UnitOwnership.php
19 ./app/Shared/Infrastructure/Models/Estate/EstateDocument.php
20 ./app/Shared/Infrastructure/Models/Estate/EstateUtilityServiceInvoice.php
34 ./app/Shared/Infrastructure/Models/Estate/Estate.php
25 ./app/Shared/Infrastructure/Models/Estate/EstateUtilityService.php
7 ./app/Shared/Infrastructure/Logging/Constants/LogChannels.php
138 ./app/Shared/Infrastructure/Repositories/Eloquent/EloquentEstateMaintenanceExpensesRepository.php
97 ./app/Shared/Infrastructure/Repositories/Eloquent/EloquentTransactionRepository.php
132 ./app/Shared/Infrastructure/Repositories/Eloquent/EloquentEstateRepository.php
180 ./app/Shared/Infrastructure/Repositories/Eloquent/EloquentUnitContractRepository.php
202 ./app/Shared/Infrastructure/Repositories/Eloquent/EloquentOwnerRepository.php
157 ./app/Shared/Infrastructure/Repositories/Eloquent/EloquentRentInvoiceRepository.php
50 ./app/Shared/Infrastructure/Repositories/Eloquent/EloquentOwnerInGroupRepository.php
127 ./app/Shared/Infrastructure/Repositories/Eloquent/EloquentOwnerGroupRepository.php
118 ./app/Shared/Infrastructure/Repositories/Eloquent/EloquentEstateDocumentRepository.php
35 ./app/Shared/Infrastructure/Repositories/Eloquent/EloquentSettingRepository.php
175 ./app/Shared/Infrastructure/Repositories/Eloquent/EloquentRenterRepository.php
150 ./app/Shared/Infrastructure/Repositories/Eloquent/EloquentEstateUtilityServiceRepository.php
91 ./app/Shared/Infrastructure/Repositories/Eloquent/EloquentEstateUtilityServiceInvoiceRepository.php
107 ./app/Shared/Infrastructure/Repositories/Eloquent/EloquentUnitUtilityServiceRepository.php
62 ./app/Shared/Infrastructure/Repositories/Eloquent/EloquentUnitOwnershipRepository.php
137 ./app/Shared/Infrastructure/Repositories/Eloquent/EloquentUnitRepository.php
82 ./app/Shared/Infrastructure/Providers/SharedServiceProvider.php
24 ./app/Shared/Application/Utility/UtilityStorageDir.php
61 ./app/Shared/Application/Utility/Month.php
10 ./app/Shared/Application/Contracts/Storage/StorageDir.php
8 ./app/Shared/Application/Contracts/Storage/Storage.php
12 ./app/Shared/Application/Contracts/Storage/File.php
